## log级别控制 logging.level：日志级别控制前缀，*为包名或Logger名 # LEVEL：选项TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
    config: classpath:config/logback-spring.xml
## Server
server:
  port: 8080
  tomcat:
      uriEncoding: UTF-8
## 数据库访问配置
spring:
    ##jsp##
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://122.114.146.179:3377/wmms?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: song1234
        # 下面为连接池的补充设置，应用到上面所有数据源中
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        logSlowSql: true

    encoding:
        force: true

    http:
      encoding:
        charset: UTF-8
        enabled: true
        
    thymeleaf:
        cache:
            false
## Mybatis 配置
mybatis:
    mapper-locations: classpath:mapper/*/*.xml
    configuration:
        map-underscore-to-camel-case: true # 开启驼峰命名规则
        use-generated-keys: true  # 使用jdbc的getGeneratedKeys 获取数据库自增主键
        use-column-label: true # 使用列名替换别名 默认为true

# 通用mapper
mapper:
    #mappers 多个接口时逗号隔开
    mappers: com.ncms.config.mybatis.MyMapper
    not-empty: false
    identity: MYSQL

